users/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

whetherornot_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.views.generic.base import TemplateView
# from whetherornot import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('whetherornot.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

whetherornot/forms.py
from django import forms
from django.views.generic.edit import FormView

# from .models import CustomUser


class CustomLocationForm(forms.Form):
    location = forms.CharField(label='Location', max_length=100)
    date = forms.DateField(label='Desired Date')

    # def got_it(self):
    #     print('--------------- got it called ------------')
    #     print('date is: ', self.cleaned_data['date'])
    #     print('--------------- got it called ------------')

    # class Meta():
    #     # model = CustomUser
    # fields = ('location')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, \
      initial-scale=1, shrink-to-fit=no">

      <title>
        {% block title %}
          Whether or Not App
        {% endblock title %}
      </title>
      <link href="{% static 'css/base.css' %}" rel="stylesheet">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    </head>
    <body>
   <nav class="navbar navbar-expand-md navbar-light bg-white mb-4 mb-0">
      <a class="navbar-brand" href="{% url 'search' %}">Whether Or Not</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse"\
      data-target="#navbarCollapse" aria-controls="navbarCollapse"\
      aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link dropdown-toggle" href="#" id="userMenu"\
              data-toggle="dropdown" aria-haspopup="true" aria-expanded\
              ="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right"\
              aria-labelledby="userMenu">
                <a class="dropdown-item" href="{% url 'password_change'\
                %}">Change password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">
                Log Out</a>
              </div>
            </li>
          </ul>
        {% else %}
          <form class="form-inline ml-auto">
            <a href="{% url 'login' %}" id="login" class="btn btn-outline-secondary">
            Log In</a>
            <a href="{% url 'signup' %}" class="btn btn-primary ml-2">
            Sign up</a>
          </form>
        {% endif %}
      </div>
    </nav>
    <div id="banner">
      <div id="cloud-scroll">
        <div class="container">
          {% block content %}
          {% endblock content %}
        </div>
      </div>
    </div>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"\ integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4\
    YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/\
    JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

templates/home.html
{%  extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
{% comment %} {% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a> |  
  <a href="{% url 'signup' %}">Sign Up</a>
{% endif %} {% endcomment %}
    {% comment %} <div id="banner"> {% endcomment %}
      {% comment %} <div id="cloud-scroll"> {% endcomment %}
        <h1 align="center" ">Welcome</h1>
        <br><br><br><br>
        {% block body_content %}
          <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Check Weather" />
            {% comment %} <p alig="center">
              <label for="id_location">Location:</label>
              <textarea name="location" id="id_location" required></textarea>
              <input type="submit" value="Check Weather" />
            </p> {% endcomment %}
          </form>
        {% endblock body_content %}
      {% comment %} </div> {% endcomment %}
  {% comment %} </div> {% endcomment %}
{% endblock content %}

templates/result.html
{%  extends 'base.html' %}

{% block title %}Result{% endblock title %}

{% block content %}
    <br><br>
    {% block body_content %}
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col-sm">
                    Date is:  {{ date     }}
                </div>
                <div class="col-sm">
                    Location is:  {{ location | capfirst }}
                </div>
                <div class="col-sm">
                    Predicted temp is:  {{ predicted_temp }}
                </div>
            </div>
        </div>
        <br><br>
        <span>
            <img src="{{MEDIA_URL}}{{ temp_image }}">
            <img src="{{MEDIA_URL}}{{ wind_image }}">
            <img src="{{MEDIA_URL}}{{ precip_image }}">
            <img src="{{MEDIA_URL}}{{ cloudcover_image }}">
        </span>
    {% endblock body_content %}
{% endblock content %}

templates/search.html
{%  extends 'base.html' %}

{% block title %}Whether or Not App Home{% endblock title %}

{% block content %}
  {% if user.is_authenticated %}
    <h1 align="center" ">Welcome {{ user.username }}</h1>
    <br><br><br><br>
    {% block body_content %}
      <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Check Weather" />
      </form>
    {% endblock body_content %}
  {% else %}
    <div class="container" align="center">
      <h2>You are not logged in<h2>
      <a href="{% url 'login' %}">Log In</a> |  
      <a href="{% url 'signup' %}">Sign Up</a>
    </div>  
  {% endif %} 
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up or Sign In{% endblock title %}

{% block content %}
<h2 align="center">Sign Up or Sign In</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign Up</button>
</form>
{% endblock content %}